---
ID: "3888bfa0-6660-475b-a963-a597453bb648"
Parent: "6b73cce8-ee17-4a24-a1f3-f7e3643be83f"
Template: "6b73cce8-ee17-4a24-a1f3-f7e3643be83f"
Path: /sitecore/templates/Project/MvpSite/Folders/Reviewer Types Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{35F14864-9753-414D-A7A8-A6EF5D808EE7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220305T095820Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ab0c5c31-58ab-46ee-ba7f-e0b4560c3c2b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220305T095831Z
