---
ID: "7e80b064-0e19-4441-985f-da645f9ad7be"
Parent: "35f14864-9753-414d-a7a8-a6ef5d808ee7"
Template: "35f14864-9753-414d-a7a8-a6ef5d808ee7"
Path: /sitecore/templates/Project/MvpSite/Content Types/Reviewer Type/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0489fbd6-8df7-4973-97c4-25e6e7a3b032"
      Hint: Text
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220305T095709Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eba48828-1874-4de1-86f6-5c4fefb811e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220305T095713Z
