---
ID: "66da0ff0-a674-4dcb-8880-d8b76abc1724"
Parent: "fd8c2f22-97e4-4f62-8ed4-a9e7c2d906b8"
Template: "fd8c2f22-97e4-4f62-8ed4-a9e7c2d906b8"
Path: /sitecore/templates/Project/MvpSite/Content Types/Review Status/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0bdc9a2b-e698-4645-a29f-7ff5ec6211fa"
      Hint: Text
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220305T094753Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8e225199-a494-4657-949d-4309f7478c2d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220305T094803Z
